// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using project.Data;

#nullable disable

namespace project.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("project.Manage.Models.DonationsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("DonorsId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PriceTiket")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DonorsId");

                    b.ToTable("DonationsModel");
                });

            modelBuilder.Entity("project.Manage.Models.DonorsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DonorsModel");
                });

            modelBuilder.Entity("project.Manage.Models.PurchasesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DonationId")
                        .HasColumnType("int");

                    b.Property<int>("DonationsId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ShoppingCartId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DonationsId");

                    b.HasIndex("ShoppingCartId");

                    b.HasIndex("UserId");

                    b.ToTable("PurchasesModel");
                });

            modelBuilder.Entity("project.Manage.Models.RandonModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DonationId")
                        .HasColumnType("int");

                    b.Property<int?>("DonationsId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RaffleDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WinningPurchaseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DonationsId");

                    b.HasIndex("WinningPurchaseId");

                    b.ToTable("RandonModel");
                });

            modelBuilder.Entity("project.Models.Customer.GiftShoppingCartModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DonationId")
                        .HasColumnType("int");

                    b.Property<int?>("DonationsId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ShoppingCartId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DonationsId");

                    b.HasIndex("ShoppingCartId");

                    b.ToTable("GiftShoppingCartModel");
                });

            modelBuilder.Entity("project.Models.Customer.ShoppingCartModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ShoppingCartModel");
                });

            modelBuilder.Entity("project.Models.Customer.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserModel");
                });

            modelBuilder.Entity("project.Manage.Models.DonationsModel", b =>
                {
                    b.HasOne("project.Manage.Models.DonorsModel", "Donors")
                        .WithMany("Donations")
                        .HasForeignKey("DonorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Donors");
                });

            modelBuilder.Entity("project.Manage.Models.PurchasesModel", b =>
                {
                    b.HasOne("project.Manage.Models.DonationsModel", "Donations")
                        .WithMany()
                        .HasForeignKey("DonationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("project.Models.Customer.ShoppingCartModel", "ShoppingCart")
                        .WithMany()
                        .HasForeignKey("ShoppingCartId");

                    b.HasOne("project.Models.Customer.UserModel", "User")
                        .WithMany("Purchases")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Donations");

                    b.Navigation("ShoppingCart");

                    b.Navigation("User");
                });

            modelBuilder.Entity("project.Manage.Models.RandonModel", b =>
                {
                    b.HasOne("project.Manage.Models.DonationsModel", "Donations")
                        .WithMany()
                        .HasForeignKey("DonationsId");

                    b.HasOne("project.Manage.Models.PurchasesModel", "WinningPurchase")
                        .WithMany()
                        .HasForeignKey("WinningPurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Donations");

                    b.Navigation("WinningPurchase");
                });

            modelBuilder.Entity("project.Models.Customer.GiftShoppingCartModel", b =>
                {
                    b.HasOne("project.Manage.Models.DonationsModel", "Donations")
                        .WithMany()
                        .HasForeignKey("DonationsId");

                    b.HasOne("project.Models.Customer.ShoppingCartModel", "ShoppingCart")
                        .WithMany("GiftShoppingCart")
                        .HasForeignKey("ShoppingCartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Donations");

                    b.Navigation("ShoppingCart");
                });

            modelBuilder.Entity("project.Models.Customer.ShoppingCartModel", b =>
                {
                    b.HasOne("project.Models.Customer.UserModel", "User")
                        .WithMany("ShoppingCarts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("project.Manage.Models.DonorsModel", b =>
                {
                    b.Navigation("Donations");
                });

            modelBuilder.Entity("project.Models.Customer.ShoppingCartModel", b =>
                {
                    b.Navigation("GiftShoppingCart");
                });

            modelBuilder.Entity("project.Models.Customer.UserModel", b =>
                {
                    b.Navigation("Purchases");

                    b.Navigation("ShoppingCarts");
                });
#pragma warning restore 612, 618
        }
    }
}
